spring.application.name=Bank Customer API

# ------ H2 Database Configuration ------
spring.datasource.url=jdbc:h2:file:./customerdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

# ------ JPA/Hibernate Configuration ------
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
